### PR TITLE
Feature/image manipulate

### PR DESCRIPTION
**Pull request by CR3Swapper**
added image manipulation functionality. its not tested, merge once its tested

### CODE REVIEW

**Comment by CR3Swapper** [comment]
please test my image manipulation code on your systems and determine if there are any bugs. ill do the same. merge once @The-MC-0 reviews the code.

**Comment by CR3Swapper** [comment]
https://github.com/BhavikChand/cst205-final-project/issues/2

**Comment by mike-dc-ca** [comment]
missing chromatic abberation

**Comment by CR3Swapper** [comment]
@The-MC-0 good for you to test again. 

> missing chromatic abberation

**Pull request merged**
